export const PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL="PLACE_ORDER_FAIL";


export const DELIVER_ORDER_REQUEST="DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_SUCCESS="DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAIL="DELIVER_ORDER_FAIL";

export const GET_USER_ORDERS_REQUEST="GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS="GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAIL="GET_USER_ORDERS_FAIL";


export const GET_ALL_ORDERS_REQUEST="GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS="GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL="GET_ALL_ORDERS_FAIL";

