export const GET_PIZZAS_REQUEST="GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS="GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAIL="GET_PIZZAS_FAIL";

export const ADD_PIZZA_REQUEST="ADD_PIZZA_REQUEST";
export const ADD_PIZZA_SUCCESS="ADD_PIZZA_SUCCESS";
export const ADD_PIZZA_FAIL="ADD_PIZZA_FAIL";

export const EDIT_PIZZA_REQUEST="EDIT_PIZZA_REQUEST";
export const EDIT_PIZZA_SUCCESS="EDIT_PIZZA_SUCCESS";
export const EDIT_PIZZA_FAIL="EDIT_PIZZA_FAIL";


export const DELETE_PIZZA_REQUEST="DELETE_PIZZA_REQUEST";
export const DELETE_PIZZA_SUCCESS="DELETE_PIZZA_SUCCESS";
export const DELETE_PIZZA_FAIL="DELETE_PIZZA_FAIL";


export const GET_PIZZA_BY_ID_REQUEST="GET_PIZZA_BY_ID_REQUEST";
export const GET_PIZZA_BY_ID_SUCCESS="GET_PIZZA_BY_ID_SUCCESS";
export const GET_PIZZA_BY_ID_FAIL="GET_PIZZA_BY_ID_FAIL";
