export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";

export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";

export const LOGOUT_USER_REQUEST="LOGOUT_USER_REQUEST"
export const LOGOUT_USER_SUCCESS="LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL="LOGOUT_USER_FAIL"

export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL="DELETE_USER_FAIL"

export const GET_ALL_USERS_REQUEST="GET_ALL_USERS_REQUEST"
export const GET_ALL_USERS_SUCCESS="GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL="GET_ALL_USERS_FAIL"